#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

$climate = new League\CLImate\CLImate;

// Who doesn't love ASCII art?
$climate->addArt('resources/ascii');
$climate->draw('phpem');

// nicely pad things for neat content display
$padding = $climate->padding(15)->char(' ');

$climate->info('The details of our next talk are as follows:');
$padding->label('Subject')->result('What to expect from PHP 7');
$padding->label('Speaker')->result('Lorna Mitchell (@lornajane) ');
$padding->label('Date & Time')->result('Thursday, August 6, 2015 at 7pm');
$padding->label('Location')->result('De Montfort University, The Gateway, Room 3.13, LE1 9BH');

$climate->br();

$climate->info('Where to find us!');
$padding->label('Website')->result('http://phpem.uk');
$padding->label('Events')->result('http://www.meetup.com/ugPHPem/');
$padding->label('Twitter')->result('http://twitter.com/phpem');