#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

$httpClient = new GuzzleHttp\Client();

$response = $httpClient->get('https://phpem-talks.herokuapp.com/');

$event = json_decode($response->getBody()->getContents(), true);

$climate = new League\CLImate\CLImate;

// Who doesn't love ASCII art?
$climate->addArt('resources/ascii');
$climate->draw('phpem');

// nicely pad things for neat content display
$padding = $climate->padding(15)->char(' ');

$climate->info('The details of our next talk are as follows:');
$padding->label('Subject')->result($event['subject']);
$padding->label('Speaker')->result($event['speaker']);
$padding->label('Date & Time')->result($event['date_time']);
$padding->label('Location')->result($event['location']);

$climate->br();

$climate->info('Where to find us!');
$padding->label('Website')->result('http://phpem.uk');
$padding->label('Events')->result('http://www.meetup.com/ugPHPem/');
$padding->label('Twitter')->result('http://twitter.com/phpem');
$padding->label('Slack')->result('http://slack.phpem.uk/');
